### ISSUE TITLE
src/ssl.c:404:9: error: unknown type name 'COMP_METHOD'

### ISSUE THREAD

**Issue by hdatma** [brunoos/luasec#65] opened 2015-12-23 08:10 UTC
The following holds for https://luarocks.org/modules/luarocks/luasec, 
which is the most downloaded code, and is one year old. 

src/ssl.c:404:9: error: unknown type name 'COMP_METHOD'; did you mean 'CONF_METHOD'?
  const COMP_METHOD *comp;
        ^~~~~~~~~~~
        CONF_METHOD
/opt/share/libressl/include/openssl/conf.h:86:31: note: 'CONF_METHOD' declared here
typedef struct conf_method_st CONF_METHOD;
                              ^
1 error generated.

Error: Build error: Failed compiling object src/ssl.o

note:

>search -cv COMP_METHOD /opt/share/libressl
/opt/share/libressl/include/openssl/comp.h:14:typedef struct comp_method_st {
/opt/share/libressl/include/openssl/comp.h:26:} COMP_METHOD;
/opt/share/libressl/include/openssl/comp.h:29:	COMP_METHOD *meth;
/opt/share/libressl/include/openssl/comp.h:39:COMP_CTX *COMP_CTX_new(COMP_METHOD *meth);
/opt/share/libressl/include/openssl/comp.h:45:COMP_METHOD *COMP_rle(void );
/opt/share/libressl/include/openssl/comp.h:46:COMP_METHOD *COMP_zlib(void );

**Comment by daurnimator** [comment] 2015-12-23 09:07
Duplicate of issue #29. Fixed via #30.

**Comment by hdatma** [comment] 2015-12-23 12:05
The problem is the absence of the fix in the mainstream distribution via luarocks, 
which is one year old.

**Comment by brunoos** [comment] 2015-12-24 11:53
Email sent to luarocks requesting update.

**Closed by brunoos** 2015-12-24 11:53 UTC
